// Auto-generated. Do not edit.
#pragma once
#include <stdint.h>

typedef enum {
  MENU_ROOT,
  MENU_MATERIALS,
  MENU_IHEATER_LINK_PLA_TEMP,
  MENU_IHEATER_LINK_PETG_TEMP,
  MENU_IHEATER_LINK_ABS_TEMP,
  MENU_IHEATER_LINK_ASA_TEMP,
  MENU_IHEATER_LINK_PC_TEMP,
  MENU_IHEATER_LINK_PA_TEMP,
  MENU_IHEATER_LINK_PA6_TEMP,
  MENU_IHEATER_LINK_PA11_TEMP,
  MENU_IHEATER_LINK_PA12_TEMP,
  MENU_IHEATER_LINK_PA66_TEMP,
  MENU_IHEATER_LINK_PMMA_TEMP,
  MENU_IHEATER_LINK_POM_TEMP,
  MENU_IHEATER_LINK_PP_TEMP,
  MENU_IHEATER_LINK_PS_TEMP,
  MENU_IHEATER_LINK_PVDF_TEMP,
  MENU_IHEATER_LINK_TPI_TEMP,
  MENU_IHEATER_LINK_PBT_TEMP,
  MENU_IHEATER_LINK_PPE_TEMP,
  MENU_IHEATER_LINK_PEI_TEMP,
  MENU_IHEATER_LINK_PEKK_TEMP,
  MENU_IHEATER_LINK_PES_TEMP,
  MENU_IHEATER_LINK_PPA_TEMP,
  MENU_IHEATER_LINK_PPS_TEMP,
  MENU_IHEATER_LINK_PEEK_TEMP,
  MENU_IHEATER_LINK_PPSU_TEMP,
  MENU_IHEATER_LINK_PSU_TEMP,
  MENU_HEATING,
  MENU_HEAT_TEMP,
  MENU_HEAT_DURATION,
  MENU_HEAT_START,
  MENU_HEAT_STOP,
  MENU_LOGS,
  MENU_LOG_PORTAL_ENABLED,
  MENU_LOG_PRINTER_ENABLED,
  MENU_LOG_DEVICE_ENABLED,
  MENU_LOG_DEBUG_ENABLED,
  MENU_IGNORE_EXTERNAL_CMD,
  MENU_UNITS_COUNT,
  MENU_LANGUAGE,
  MENU__COUNT
} MenuId;

typedef enum {
  LANG_RU = 0,
  LANG_EN = 1,
  LANG_COUNT
} LangId;
